### PR TITLE
chore(docker-tag): do not fail if tag already exists - v3

### PR DESCRIPTION
**Pull request by floriantz**
Third try to make this change, github workflows actually sets `shell: bash -e {0}` by default cf [doc](https://github.com/sencrop/github-workflows/pull/176) which makes an intermediate command failure fail the entire script.

Setting `shell: bash {0}` to override the default should finally fix the issue.

### CODE REVIEW

**Comment by jdassonvil** [comment]
you are replacing something non explicit by something else non explicit
you should use `set +e` instead

you might also set more flags to avoid suprises: http://redsymbol.net/articles/unofficial-bash-strict-mode/

**Comment by floriantz** [comment]
> you are replacing something non explicit by something else non explicit you should use `set +e` instead at the beginning of the script
> 
> you might also set more flags to avoid surprises: http://redsymbol.net/articles/unofficial-bash-strict-mode/

I think setting `+e` should be enough in this case right ?

**Comment by jdassonvil** [comment]
yes it is enough
but what we should do all the time is begin all bash script by the strict mode instructions (I don't so I also blame myself here)
and then changes the flags when necessary

**Comment by jdassonvil** [comment]
yes it is enough
but what we should do all the time is begin all bash script by the strict mode instructions (I don't so I also blame myself here)
and then changes the flags when necessary

**Review by jdassonvil — APPROVED** [review]

**Pull request merged**
